version: ~> 1.0
language: c
os: linux
jobs:
  include:
  - stage: "Build and test"
    compiler: gcc
    os: linux
    dist: bionic
  - compiler: clang
    os: linux
    dist: bionic
  - compiler: gcc
    os: linux
    dist: xenial
  - compiler: clang
    os: linux
    dist: xenial
  - compiler: gcc
    os: linux
    dist: trusty
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
  - compiler: clang
    os: linux
    dist: trusty
  - os: windows
    cache:
      directories:
        - $HOME/AppData/Local/Temp/chocolatey
  - os: osx
git:
  autocrlf: false
addons:
  apt:
    update: true
before_script:
  - mkdir build
  - cd build
script: cmake .. && cmake --build .
