version: ~> 1.0
language: c
os: linux
dist: xenial
jobs:
  include:
  - stage: "Build and test"
    compiler: gcc
    os: linux
    dist: bionic
  - compiler: clang
    os: linux
    dist: bionic
  - compiler: gcc
    os: linux
    dist: xenial
  - compiler: clang
    os: linux
    dist: xenial
  - os: windows
    cache:
      directories:
        - $HOME/AppData/Local/Temp/chocolatey
    install:
      - mkdir libbuild
      - mkdir libinstall
      - curl -L -O https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz
      - 7z x cmocka-1.1.5.tar.xz
      - 7z x cmocka-1.1.5.tar
      - cd libbuild
      - cmake -DCMAKE_INSTALL_PREFIX="$PWD/../libinstall" "$PWD/../cmocka-1.1.5"
      - cmake --build . --config Release
      - cmake --install . --config Release
      - cd ..
    script: cmake -Werror=dev -Werror=deprecated .. -DCMocka_DIR="$PWD/../libinstall/lib/cmake/cmocka" && cmake --build . --config Debug && cp "$PWD/../libinstall/bin/cmocka.dll" "$PWD/libcatoolbox/Debug/cmocka.dll" && ctest
  - os: osx
    install:
      - brew install cmocka
git:
  autocrlf: false
addons:
  apt:
    update: true
    packages:
      - libcmocka0
      - libcmocka-dev
before_script:
  - mkdir build
  - cd build
script: cmake -Werror=dev -Werror=deprecated .. && cmake --build . && ctest
